export const releaseStatusesList: string[] = [
  "Launched",
  "In development",
  "Rolling out",
  "Cancelled",
];

export const releasePhasesList: string[] = [
  "Preview",
  "Beta Channel",
  "General Availability",
  "Targeted Release",
  "Targeted Release (Entire Organization)",
  "Targeted Release (Select People)",
  "Limited Availability",
  "Semi-annual (Standard)",
  "Semi-Annual Enterprise Channel",
  "Semi-Annual Enterprise Channel (Preview)",
  "Monthly Enterprise Channel",
  "Monthly Channel (Standard)",
  "Current Channel (Preview)",
  "Current Channel",
];

export const cloudInstancesList: string[] = [
  "Worldwide (Standard Multi-Tenant)",
  "DoD",
  "GCC",
  "GCC High",
];

export const platformsList: string[] = [
  "Android",
  "Desktop",
  "Developer",
  "Education",
  "iOS",
  "Linux",
  "Mac",
  "Mobile",
  "Teams and Surface Devices",
  "Web",
];

export const productsList: string[] = [
  "Access",
  "Azure Active Directory",
  "Azure Information Protection",
  "Bookings",
  "Excel",
  "Exchange",
  "Forms",
  "Microsoft 365",
  "Microsoft 365 Admin Center",
  "Microsoft 365 app",
  "Microsoft 365 Copilot",
  "Microsoft 365 Defender",
  "Microsoft Clipchamp",
  "Microsoft Cloud App Security",
  "Microsoft Compliance center",
  "Microsoft Copilot for Microsoft 365",
  "Microsoft Defender for Cloud Apps",
  "Microsoft Defender for Endpoint",
  "Microsoft Defender for Identity",
  "Microsoft Defender for Office 365",
  "Microsoft Edge",
  "Microsoft Endpoint Manager",
  "Microsoft Entra",
  "Microsoft Graph",
  "Microsoft Information Protection",
  "Microsoft Intune",
  "Microsoft Loop",
  "Microsoft Power Apps",
  "Microsoft Project",
  "Microsoft Purview compliance portal",
  "Microsoft Search",
  "Microsoft Stream",
  "Microsoft Syntex",
  "Microsoft Teams",
  "Microsoft To Do",
  "Microsoft Viva",
  "Minecraft Education",
  "MyAnalytics",
  "Office 365",
  "Office 365 Groups",
  "Office app",
  "OneDrive",
  "OneNote",
  "Outlook",
  "Planner",
  "PowerApps",
  "Power Automate",
  "Power BI",
  "PowerPoint",
  "Project",
  "Skype for Business",
  "SharePoint",
  "SharePoint Syntex",
  "TeamsAndSurfaceDevices",
  "Universal Print",
  "Visio",
  "Whiteboard",
  "Windows",
  "Windows 10",
  "Windows 11",
  "Windows 365",
  "Word",
  "Yammer",
];

export const tagList: string[] = releaseStatusesList.concat(
  releasePhasesList,
  cloudInstancesList,
  platformsList,
  productsList
);
