name: Weekly summary

# Run every Sunday one hour later than the RSS watcher
on:
  schedule:
    - cron: "0 3 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run script
        id: checker
        run: ./Generate-WeeklyDiff.ps1
      - name: Commit changes
        run: |
          git add .
          git config --global user.name 'Robert Dyjas'
          git config --global user.email '15113729+robdy@users.noreply.github.com'
          git commit -am "$(Get-Date -Format 'yyyy-MM-dd') weekly summary"
          git push